// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtiufGjr-lMTOSsdzUBs_BSHzYTewSM3I',
    appId: '1:938402632874:android:62f283b65e4ca49ca9acd3',
    messagingSenderId: '938402632874',
    projectId: 'evently-a7dc9',
    storageBucket: 'evently-a7dc9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOxlxULUzC5LBkcaGjbwKwUYlClYjVTQg',
    appId: '1:938402632874:ios:0cfd2834ef4191afa9acd3',
    messagingSenderId: '938402632874',
    projectId: 'evently-a7dc9',
    storageBucket: 'evently-a7dc9.firebasestorage.app',
    androidClientId: '938402632874-42ha4np3uj7lu7vbku6aka4ak62a2qma.apps.googleusercontent.com',
    iosClientId: '938402632874-fqmfikbnf5o8q83h794lq7q3cq8a7ggj.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventlyC19',
  );
}
